#!/usr/bin/env bash
# transfers a file for a client
# to a server

if [ -z "$4" ];
then
  echo "$0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit
fi

scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
